// <auto-generated />
namespace moeKino.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class requiredKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requiredKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201808151355437_requiredKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
