// <auto-generated />
namespace moeKino.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedTimeInModelFilm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedTimeInModelFilm));
        
        string IMigrationMetadata.Id
        {
            get { return "201809031752424_addedTimeInModelFilm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
